from PIL import Image
import os

image = Image.open("monro.jpg")
red_image, green_image, blue_image = image.split()
red_image = red_image.save("monroRed.jpg")
green_image = green_image.save("monroGreen.jpg")
blue_image = blue_image.save("monroBlue.jpg")
red_image = Image.open("monroRed.jpg")
coordinates = (50, 0, red_image.width, red_image.height)
cropped = red_image.crop(coordinates)
cropped.save("monroRedRight.jpg")
red_image = Image.open("monroRed.jpg")
coordinates = (25, 0, red_image.width - 25, red_image.height)
cropped = red_image.crop(coordinates)
cropped.save("monroRedMiddle.jpg")
blue_image = Image.open("monroBlue.jpg")
coordinates = (25, 0, blue_image.width - 25, blue_image.height)
cropped = blue_image.crop(coordinates)
cropped.save("monroBlueMiddle.jpg")
blue_image = Image.open("monroBlue.jpg")
coordinates = (0, 0, blue_image.width - 50, blue_image.height)
cropped = blue_image.crop(coordinates)
cropped.save("monroBlueLeft.jpg")
green_image = Image.open("monroGreen.jpg")
coordinates = (25, 0, green_image.width - 25, green_image.height)
cropped = green_image.crop(coordinates)
cropped.save("monroGreenMiddle.jpg")
red_image_right = Image.open("monroRedRight.jpg")
red_image = Image.open("monroRedMiddle.jpg")
imageMerger = Image.blend(red_image_right, red_image, 0.5)
imageMerger.save("monroRedMerger.jpg")
blue_image_left = Image.open("monroBlueLeft.jpg")
blue_image = Image.open("monroBlueMiddle.jpg")
imageMerger = Image.blend(blue_image_left, blue_image, 0.5)
imageMerger.save("monroBlueMerger.jpg")
red_image = Image.open("monroRedMerger.jpg")
green_image = Image.open("monroGreenMiddle.jpg")
image_blue = Image.open("monroBlueMerger.jpg")
new_image = Image.merge("RGB", (red_image, green_image, image_blue))
new_image.save("monroRGB.jpg")
new_image.thumbnail((80, 80))
new_image.save("monroRGBavatar.jpg")
os.remove("monroBlue.jpg")
os.remove("monroBlueLeft.jpg")
os.remove("monroBlueMerger.jpg")
os.remove("monroBlueMiddle.jpg")
os.remove("monroGreen.jpg")
os.remove("monroGreenMiddle.jpg")
os.remove("monroRed.jpg")
os.remove("monroRedMerger.jpg")
os.remove("monroRedMiddle.jpg")
os.remove("monroRedRight.jpg")
os.remove("monroRGB.jpg")
