from PIL import Image
import os

image = Image.open("monro.jpg")
red_image, green_image, blue_image = image.split()
coordinates_red_right = (50, 0, red_image.width, red_image.height)
crop_red_right = red_image.crop(coordinates_red_right)
coordinates_red = (25, 0, red_image.width - 25, red_image.height)
crop_red = red_image.crop(coordinates_red)
coordinates_blue = (25, 0, blue_image.width - 25, blue_image.height)
crop_blue = blue_image.crop(coordinates_blue)
coordinates_blue_left = (0, 0, blue_image.width - 50, blue_image.height)
crop_blue_left = blue_image.crop(coordinates_blue_left)
coordinates_green_middle = (25, 0, green_image.width - 25, green_image.height)
crop_green_middle = green_image.crop(coordinates_green_middle)
image_merger_red = Image.blend(crop_red_right, crop_red, 0.5)
image_merger_blue = Image.blend(crop_blue_left, crop_blue, 0.5)
new_image = Image.merge("RGB", (image_merger_red, crop_green_middle, image_merger_blue))
new_image.thumbnail((80, 80))
new_image.save("monroRGBavatar.jpg")
